version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Admin-Access
      POSTGRES_USER: Admin
      POSTGRES_DB: StudentDb
  app:
    image: my-node-app
    ports:
      - "13000:3000"
